// Gera HTML estático: cabeçalho e rodapé possuem uma única fonte para todas as páginas.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..');
const read = file => fs.readFileSync(path.join(root, file), 'utf8');
const write = (file, value) => fs.writeFileSync(path.join(root, file), (file.endsWith('.html') ? value.replace(/>[ \t]*</g, '>\n<') : value).split('\n').map(line=>line.trimEnd()).join('\n'));
const source = read('templates/home.html');
const extract = (start, end) => source.slice(source.indexOf(start), source.indexOf(end, source.indexOf(start)));
const whatsapp = source.match(/<a class="header-whatsapp"[\s\S]*?<\/a>/)[0];
const nav = [['index.html','Início'],['ms-project.html','MS Project'],['primavera.html','Primavera'],['certificacao-pmp.html','Certificação PMP'],['agenda.html','Agenda de Treinamentos'],['sobre.html','Sobre a Pavel']];
function header(current) { return `<header class="site-header"><div class="header-inner"><a class="brand" href="index.html" aria-label="Pavel Consultoria — início"><img class="brand-image" src="assets/logo-pavel-dark.png" alt="Pavel Consultoria" width="2172" height="724" decoding="async"></a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="menu">Menu <span aria-hidden="true">☰</span></button><nav id="menu" aria-label="Navegação principal">${nav.map(([url,label])=>`<a href="${url}"${url===current?' aria-current="page"':''}>${label}</a>`).join('')}</nav>${whatsapp}</div></header>`; }
const originalFooter = source.match(/<footer class="container footer">[\s\S]*?<\/footer>/)[0];
const channels = originalFooter.match(/<div class="footer-channels">[\s\S]*?<\/div><\/div>/)[0];
const footer = `<footer class="container footer"><div class="footer-identity"><strong>PAVEL CONSULTORIA</strong><p>Planejamento e Gestão de Cronogramas</p></div><div class="footer-contact"><p class="footer-name">Karolina Poznyakov, MSc, PMP (retired), IPMA-D</p>${channels}</div><div class="footer-status"><time id="footer-clock" aria-label="Data e hora de Brasília"></time><p class="footer-visits"><span aria-hidden="true">👁</span> Visitas: <span id="site-visits" aria-live="polite">indisponível</span></p></div></footer>`;
const float = `<a class="whatsapp-floating" href="https://wa.me/5521995716270" data-whatsapp="geral" aria-label="Fale conosco pelo WhatsApp" target="_blank" rel="noopener noreferrer"><svg viewBox="0 0 32 32" aria-hidden="true">${whatsapp.match(/<svg[^>]*>([\s\S]*?)<\/svg>/)[1]}</svg></a>`;
const quotes = {
 home:[['Rubens Santos','Obrigado por transbordar seu conhecimento Karolina. De fato, foi excelente o aprendizado que obtive contigo e com a Pavel Consultoria. Novamente, obrigado!!'],['Afonso Vieira Braida','Super recomendo, excelente didática e clareza.']],
 msp:[['Rubens Santos','O treinamento do MS Project, designado a planejamento e controle profissional de projetos, reforçou conhecimentos em cronogramas, dependências, recursos, linha de base, acompanhamento e análise de desvios entre planejado e realizado. […]'],['Melquisedeque Lima','Foi um treinamento excelente e que, sem dúvida, valeu muito a pena. Além do conhecimento técnico, os exemplos e a forma de condução das aulas contribuíram muito para tornar o aprendizado mais prático e aplicável ao dia a dia.'],['Afonso Vieira Braida','Super recomendo, excelente didática e clareza.']],
 p6:[['Jafet Junior','Um agradecimento especial à PAVEL CONSULTORIA (Karolina Poznyakov, MSc, PMP retired, IPMA-D) pelo excelente treinamento em Primavera P6 e por todo o suporte e orientação que contribuíram para me preparar para esta nova etapa da minha carreira.'],['Rubens Santos','Concluí minha formação em Oracle Primavera P6, Planejamento e Controle Profissional de Projetos. […]']]
};
function testimonials(key){return `<section class="testimonials container section" aria-labelledby="testimonials-title"><h2 id="testimonials-title">O que dizem nossos alunos</h2><div class="testimonial-grid">${quotes[key].map(([name,text])=>`<figure class="testimonial"><blockquote><p>“${text}”</p></blockquote><figcaption>${name}</figcaption></figure>`).join('')}</div></section>`;}
const dialog = source.match(/<dialog id="class-dialog"[\s\S]*?<\/dialog>/)[0];
const agenda = extract('    <section class="agenda-section', '    <section class="pavel-about');
const about = extract('    <section class="pavel-about', '    <section class="contact-section').replace('IPMA-D.</h3>','IPMA-D</h3>');
const contact = extract('    <section class="contact-section','  </main>');
const agendaScripts = ['assets/vendor/astronomy.browser.min.js','assets/calendar.js','assets/agenda-data.js','assets/agenda.js','assets/agenda-share.js'];
function page(file,title,content,{home=false,calendar=false,styles=[]}={}) {
 const description=title+' — consultoria especializada e treinamentos práticos Pavel.';
 write(file,`<!doctype html>\n<html lang="pt-BR"><head><meta charset="utf-8"><link rel="icon" href="assets/logo-pavel-dark.png" type="image/png"><meta name="viewport" content="width=device-width, initial-scale=1"><meta name="theme-color" content="#1b252a"><title>${title} | Pavel Consultoria</title><meta name="description" content="${description}"><link rel="canonical" href="https://pavelconsultoria.com.br/${file==='index.html'?'':file}"><meta property="og:url" content="https://pavelconsultoria.com.br/${file==='index.html'?'':file}"><meta property="og:title" content="${title} | Pavel Consultoria"><meta property="og:type" content="website"><meta property="og:locale" content="pt_BR">${['assets/styles.css',...(home?['assets/home.css']:[]),...styles,'assets/site.css'].map(s=>`<link rel="stylesheet" href="${s}">`).join('')}<script type="application/ld+json">{"@context":"https://schema.org","@type":"Organization","name":"Pavel Consultoria","url":"https://pavelconsultoria.com.br/"}</script><script defer src="assets/config.js"></script><script defer src="assets/app.js"></script><script defer src="assets/site.js"></script>${calendar?agendaScripts.map(s=>`<script defer src="${s}"></script>`).join(''):''}<script async data-goatcounter="https://pavelconsultoria.goatcounter.com/count" src="https://gc.zgo.at/count.js"></script><script defer src="assets/visits.js"></script></head><body class="${home?'home':'internal'}"><a class="skip-link" href="#conteudo">Pular para o conteúdo</a>${header(file)}<main id="conteudo">${content}</main>${footer}${home?'':float}${calendar?dialog:''}</body></html>\n`);
}
let hero = extract('    <div class="hero-stage">','    <section class="expertise');
hero=hero.replace(/<p class="eyebrow"><span class="accent-line"><\/span> PAVEL CONSULTORIA<\/p>/,'').replace(/<h1 id="hero-title">[\s\S]*?<\/h1>/,'<h1 id="hero-title">Consultoria em Gestão de Projetos, Treinamentos MS Project e Primavera e Análise Forense de Atraso em Cronogramas</h1>').replace(/<p class="hero-disciplines">[\s\S]*?<\/p>/,'<p class="hero-disciplines">Consultoria Empresarial – Treinamentos Práticos com Aplicação de Conhecimentos Adquiridos – Tecnologia Pavel</p>').replace('<div class="hero-actions">','<div class="hero-actions"><a class="home-whatsapp" href="https://wa.me/5521995716270" target="_blank" rel="noopener noreferrer" aria-label="Fale conosco pelo WhatsApp"><img src="assets/whatsapp-home.png" alt="Fale Conosco" width="440" height="147"></a>');
hero=hero.replace(/<a class="button" href="#contato"[\s\S]*?<\/a>/,'');
let expertise=extract('    <section class="expertise','    <section class="training-section');
expertise=expertise.replace(/href="https:\/\/wa.me\/5521995716270" data-whatsapp="p6"/g,'href="primavera.html"').replace('href="#treinamentos"','href="ms-project.html"').replace('href="#simulator"','href="certificacao-pmp.html"');
page('index.html','Consultoria em Gestão de Projetos',hero+expertise+testimonials('home')+contact,{home:true});
const mspBlocks=[['Estruturação do Cronograma','Planejamento e organização das atividades.'],['Lógica, Calendários e Restrições','Sequenciamento, relações e boas práticas.'],['Recursos, Custos e Nivelamento','Alocação, análise de capacidade e custos.'],['Análise e Controle do Cronograma','Caminho crítico, baseline e atualização.'],['Visualizações e Análises Avançadas','Filtros, relatórios e grandes cronogramas.'],['Projeto Prático Completo','Do planejamento ao controle.']];
const p6Blocks=[['Treinamento especializado','Primavera P6 Básico.'],['Formato','8 horas, online ao vivo.'],['Aplicação prática','Planejamento e controle de cronogramas.'],['Apostila','Material completo do treinamento.'],['Certificado','Certificado digital de conclusão verificado no Certifier.'],['Próximas turmas','Programação e inscrição na Agenda.']];
const syllabus=`<h3>Fundamentos e estruturação — Básico</h3><p>Criação e configuração do projeto • Calendários • Estrutura Analítica do Projeto (EAP/WBS) • Tarefas e marcos • Durações • Predecessoras e sucessoras • Tipos de relacionamento • Caminho crítico • Recursos • Programação e visualização do cronograma</p><h3>Planejamento e controle — Avançado</h3><p>Tipos de tarefa e comportamento de duração, trabalho e unidades • Recursos e nivelamento • Linha de base • Atualização e acompanhamento • Data de status • Duração real e restante • Uso da tarefa/recurso • Campos personalizados e fórmulas • Histograma • Curva S • Sinalizadores • Filtros, agrupamentos, tabelas e layouts • Relatórios e análise do cronograma</p>`;
for(const key of ['msp','p6']) {
 const msp=key==='msp',title=msp?'MS Project — do Básico ao Avançado':'Primavera P6 Básico',blocks=msp?mspBlocks:p6Blocks;
 const content=`<section class="course-cover course-cover--${key}"><div class="container"><a class="course-agenda text-link" href="agenda.html">Próximas turmas · Veja as datas na Agenda ↗</a><p class="eyebrow">TREINAMENTO · ${msp?'MS PROJECT':'PRIMAVERA P6'}</p><h1>${title}</h1><p class="course-intro">${msp?'Aprenda a planejar, estruturar, analisar e controlar cronogramas de projetos de forma prática e profissional.':'Treinamento especializado em Primavera P6 Básico, com aplicação prática ao planejamento e à gestão de cronogramas.'}</p><p class="course-highlights">8 horas · Online ao vivo · Turmas reduzidas · Apostila completa · Certificado digital</p><a class="button" href="agenda.html">Quero me inscrever ↗</a><h2>${msp?'O que você vai aprender':'Seu treinamento'}</h2><div class="learning-grid">${blocks.map(([name,text],i)=>`<article><span class="learning-number">${i+1}</span><h3>${name}</h3><p>${text}</p></article>`).join('')}</div><div class="course-shortcuts"><a href="#apostila">Conheça a apostila <span>Prévia e material do treinamento ↗</span></a><a href="#ementa">${msp?'Ver ementa':'Conteúdo do treinamento'} <span>Conheça os tópicos disponíveis ↗</span></a><a href="#investimento">Investimento <span>Valores confirmados e inscrição ↗</span></a></div></div></section><section class="container course-details section"><div id="ementa"><h2>${msp?'Conteúdo do treinamento':'Primavera P6 Básico'}</h2>${msp?syllabus:'<p>Treinamento especializado em Primavera P6 Básico, com carga horária de 8 horas.</p><p>A ementa detalhada será disponibilizada após confirmação. Consulte a Pavel para conhecer o conteúdo vigente.</p>'}${msp?'<p>Não é necessário conhecimento prévio de MS Project.</p><p>É desejável ter o MS Project instalado para praticar durante o treinamento.</p>':''}</div><div id="apostila"><h2>Apostila ${msp?'do MS Project':'do Primavera P6'}</h2><p>Apostila completa incluída no treinamento.</p>${msp?'<a class="button" href="assets/apostila-msproject-previa.pdf" target="_blank" rel="noopener noreferrer">Abrir prévia demonstrativa (PDF) ↗</a>':'<p class="material-pending">Prévia demonstrativa em preparação.</p>'}<a class="text-link" href="https://wa.me/5521995716270" data-whatsapp="${msp?'apostilaMsp':'apostilaP6'}">Consultar a apostila ↗</a></div><div id="investimento"><h2>Investimento</h2><p class="price">${msp?'R$ 460,00':'R$ 700,00'}</p>${msp?'<p>Valor válido para turmas a partir de novembro de 2026. Para turmas de outubro, consulte o investimento pelo WhatsApp.</p>':''}<p>Consulte condições de pagamento e disponibilidade com a Pavel.</p><a class="button" href="agenda.html">Consultar turmas e inscrição ↗</a></div><div class="certificate"><img src="assets/Certificado-digital.png" alt="Certificado de conclusão Pavel Consultoria" width="1536" height="1024" loading="lazy"><div><h2>Certificado digital de conclusão verificado no Certifier</h2><p>Ao concluir o treinamento, receba seu certificado digital.</p></div></div></section>${testimonials(key)}`;
 page(msp?'ms-project.html':'primavera.html',title,content);
}
page('certificacao-pmp.html','Certificação PMP',`<section class="pmp-cover"><div class="container"><p class="eyebrow">TECNOLOGIA PAVEL</p><h1>Certificação PMP</h1><h2>Pavel PMP Simulator</h2><p>Uma solução digital própria para apoiar sua preparação para o exame PMP.</p><p class="price">R$ 199,00</p><p>Assinatura trimestral · 90 dias</p><a class="button" href="https://pavelpmpsimulator.com.br/" target="_blank" rel="noopener noreferrer">Acessar o Simulator ↗</a></div></section><section class="container section pmp-information"><h2>Preparação com prática e diagnóstico</h2><p>Plataforma de preparação para o exame PMP®, desenvolvida pela Pavel Consultoria, com foco em prática, diagnóstico e evolução do aluno.</p><div class="pmp-columns"><div><h3>Conteúdo da plataforma</h3><ul><li>600 questões no banco atual</li><li>500 questões regulares</li><li>100 questões contextualizadas em 20 Case Studies</li><li>5 questões vinculadas a cada Case Study</li><li>Questões Single Response e Multiple Response</li><li>Modos Estudo, Exame e Revisão</li><li>Filtros por Domínio ECO, dificuldade, abordagem, tipo de resposta e área de conhecimento</li></ul></div><div><h3>Referências</h3><ul><li>PMP® 2026</li><li>ECO vigente</li><li>PMBOK® Guide – 8ª edição</li></ul></div></div><p>As faixas de desempenho utilizadas pelo Pavel PMP Simulator são referências pedagógicas internas e não representam percentual oficial de aprovação definido pelo PMI.</p></section>`);
page('agenda.html','Agenda de Treinamentos',agenda.replace('<h2 id="agenda-title">','<h1 id="agenda-title">').replace('Agenda de Treinamentos</h2>','Agenda de Treinamentos</h1>'),{calendar:true,styles:['assets/agenda.css']});
page('sobre.html','Sobre a Pavel',about.replace('<h2 id="about-title">','<h1 id="about-title">').replace('Sobre a Pavel</h2>','Sobre a Pavel</h1>')+contact,{styles:['assets/about.css']});
write('sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${nav.map(([file])=>`<url><loc>https://pavelconsultoria.com.br/${file==='index.html'?'':file}</loc></url>`).join('')}</urlset>\n`);
write('robots.txt','User-agent: *\nAllow: /\nSitemap: https://pavelconsultoria.com.br/sitemap.xml\n');
console.log('HTML estático gerado: seis páginas, cabeçalho e rodapé compartilhados.');
