// Requer Node --use-system-ca neste Windows com interceptação TLS do Avast.
// Não desabilita TLS. SSL Labs inspeciona a cadeia original fora desta máquina.
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),https=require('node:https'),http=require('node:http'),dns=require('node:dns').promises;
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),base='https://pavelconsultoria.com.br/';
const directory=path.join(root,'.preview','published');fs.mkdirSync(directory,{recursive:true});
const report={time:new Date().toISOString(),resources:[],redirects:[],external:[],dns:{},warnings:[]};
function request(url){return new Promise(resolve=>{const start=performance.now();const req=(url.startsWith('https:')?https:http).get(url,{agent:false,headers:{'User-Agent':'PavelConsultoria-publication-validation'}},res=>{const chunks=[];const cert=res.socket.getPeerCertificate?.(),authorized=res.socket.authorized;res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>resolve({url,status:res.statusCode,location:res.headers.location,type:res.headers['content-type'],milliseconds:Math.round(performance.now()-start),tlsAuthorized:authorized,certificate:cert?{subject:cert.subject,issuer:cert.issuer,names:cert.subjectaltname,from:cert.valid_from,to:cert.valid_to,fingerprint256:cert.fingerprint256}:undefined,body:Buffer.concat(chunks)}));});req.setTimeout(20000,()=>req.destroy(Error('timeout')));req.on('error',error=>resolve({url,error:error.code||error.message,milliseconds:Math.round(performance.now()-start)}));});}
async function run(){
 const pages=['index.html','ms-project.html','primavera.html','certificacao-pmp.html','agenda.html','sobre.html'];const files=new Set(pages);
 for(const page of pages){const html=fs.readFileSync(path.join(root,page),'utf8');for(const m of html.matchAll(/(?:src|href)="([^"]+)"/g)){if(!m[1].startsWith('#')&&!/^[a-z]+:/i.test(m[1]))files.add(m[1]);}}
 for(const file of [...files])if(file.endsWith('.css'))for(const m of fs.readFileSync(path.join(root,file),'utf8').matchAll(/url\(['"]?([^'")]+)['"]?\)/g))if(!m[1].startsWith('data:'))files.add(path.posix.join(path.posix.dirname(file),m[1]));
 const all=[...files];for(let i=0;i<all.length;i+=5){const results=await Promise.all(all.slice(i,i+5).map(async file=>{const r=await request(new URL(file,base).href);const expected=crypto.createHash('sha256').update(execFileSync('git',['show','HEAD:'+file],{cwd:root,maxBuffer:25*1024*1024})).digest('hex');const actual=r.body?crypto.createHash('sha256').update(r.body).digest('hex'):'';const {body,...summary}=r;return {file,...summary,bytes:body?.length,sha256:actual,matchesCommit:actual===expected};}));report.resources.push(...results);}
 for(const url of ['http://pavelconsultoria.com.br/','http://www.pavelconsultoria.com.br/','https://www.pavelconsultoria.com.br/','https://pavelconsultoria.github.io/Pavel_Consultoria/']){let current=url;const chain=[];for(let i=0;i<6;i++){const r=await request(current);const {body,...summary}=r;chain.push(summary);if(r.status>=300&&r.status<400&&r.location)current=new URL(r.location,current).href;else break;}report.redirects.push({initial:url,chain,final:current});}
 for(const type of ['A','AAAA','CAA'])try{report.dns[type]=await dns.resolve('pavelconsultoria.com.br',type);}catch(e){report.dns[type]={error:e.code};}
 try{report.dns.www=await dns.resolveCname('www.pavelconsultoria.com.br');}catch(e){report.dns.www={error:e.code};}
 const external=['https://pavelpmpsimulator.com.br/','https://wa.me/5521995716270','https://www.instagram.com/pavelconsultoria/','https://br.linkedin.com/in/pavel-consultoria-karolina-poznyakov-msc-pmp-retired-ipma-d-46933913','https://www.facebook.com/share/1DtL7kJcTF/','https://pavelconsultoria.goatcounter.com/counter/TOTAL.json','https://gc.zgo.at/count.js'];
 for(const url of external){const {body,...summary}=await request(url);report.external.push(summary);if(url.includes('TOTAL.json'))report.counter=body?.toString();}
 const sslResponse=await request('https://api.ssllabs.com/api/v3/analyze?host=pavelconsultoria.com.br&fromCache=on&all=done');if(sslResponse.body){const ssl=JSON.parse(sslResponse.body.toString());fs.writeFileSync(path.join(directory,'ssl-labs-full.json'),JSON.stringify(ssl,null,2));report.independentTLS={source:'Qualys SSL Labs',status:ssl.status,started:ssl.startTime?new Date(ssl.startTime).toISOString():undefined,endpoints:ssl.endpoints?.map(e=>({ip:e.ipAddress,grade:e.grade,warnings:e.hasWarnings,status:e.statusMessage,protocols:e.details?.protocols,sniChains:e.details?.certChains?.filter(c=>!c.noSni).map(c=>({issues:c.issues,trust:c.trustPaths.map(p=>p.trust)})),noSniChains:e.details?.certChains?.filter(c=>c.noSni).map(c=>({issues:c.issues,trust:c.trustPaths.map(p=>p.trust)})),hsts:e.details?.hstsPolicy,forwardSecrecy:e.details?.forwardSecrecy,suites:e.details?.suites})),certificates:ssl.certs?.filter(c=>c.commonNames?.includes('pavelconsultoria.com.br')).map(c=>({subject:c.subject,issuer:c.issuerSubject,names:c.altNames,from:new Date(c.notBefore).toISOString(),to:new Date(c.notAfter).toISOString(),issues:c.issues,sha256:c.sha256Hash}))};}
 report.github=await fetch('https://api.github.com/repos/PavelConsultoria/Pavel_Consultoria/actions/runs?per_page=5',{headers:{'User-Agent':'Pavel-validation'}}).then(r=>r.json()).then(d=>d.workflow_runs?.map(r=>({id:r.id,name:r.name,status:r.status,conclusion:r.conclusion,commit:r.head_sha,url:r.html_url}))).catch(e=>({error:e.message}));
 report.result=report.resources.every(r=>r.status===200&&r.matchesCommit)?'APROVADO':'PENDENTE';
 fs.writeFileSync(path.join(directory,'network-report.json'),JSON.stringify(report,null,2));console.log(JSON.stringify({result:report.result,resources:report.resources.length,failed:report.resources.filter(r=>r.status!==200||!r.matchesCommit),redirects:report.redirects.map(r=>({from:r.initial,chain:r.chain.map(c=>c.status),to:r.final})),dns:report.dns,external:report.external.map(e=>({url:e.url,status:e.status,error:e.error})),TLS:report.independentTLS?{status:report.independentTLS.status,certificates:report.independentTLS.certificates,grades:report.independentTLS.endpoints?.map(e=>({ip:e.ip,grade:e.grade}))}:null,github:report.github},null,2));if(report.result!=='APROVADO')process.exitCode=1;
}
run().catch(e=>{console.error(e);process.exitCode=1;});
